# Generated by Django 3.0.5 on 2020-04-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('featured_image', models.ImageField(upload_to='images/portfolio/')),
            ],
        ),
    ]
