# Generated by Django 3.0.5 on 2020-04-21 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_clienttestimony'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clienttestimony',
            options={'ordering': ['name']},
        ),
    ]
